/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package file_compression_uillity;

import java.io.File;

/**
 *
 * @author Abdul
 */
public class FileSelectionPanel extends javax.swing.JFrame {
    private CompressionManager compressionManager;
    private File[] selectedFiles; // Store multiple selected files

    // Prototype Pattern - stores current file selection for cloning
    private FileSelection currentSelection;

    public FileSelectionPanel() {
        initComponents();
        compressionManager = CompressionManager.getInstance();
        currentSelection = new FileSelection("Default Selection"); // Prototype Pattern
        ProgressBar.setValue(0);
        lblStatus.setText("Ready to compress files");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PathTextFiled = new javax.swing.JTextField();
        BrowseButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TypeComboBox = new javax.swing.JComboBox<>();
        CompressButton = new javax.swing.JButton();
        DecompressButton = new javax.swing.JButton();
        ProgressBar = new javax.swing.JProgressBar();
        lblStatus = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("SELECT FILE :");

        BrowseButton.setText("Browse");
        BrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("COMPRESSION TYPE :");

        TypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ZIP", "RAR" }));

        CompressButton.setText("COMPRESS");
        CompressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompressButtonActionPerformed(evt);
            }
        });

        DecompressButton.setText("DECOMPRESS");
        DecompressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecompressButtonActionPerformed(evt);
            }
        });

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStatus.setText("Status :");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("File Compression Utility");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(66, 66, 66)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                169,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(TypeComboBox,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(PathTextFiled,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                203,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(40, 40, 40)
                                                                        .addComponent(BrowseButton)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(CompressButton)
                                                                .addGap(149, 149, 149)
                                                                .addComponent(DecompressButton))
                                                        .addComponent(ProgressBar,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 237,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(122, 122, 122)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 219,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(46, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel4)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(PathTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BrowseButton))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(CompressButton)
                                        .addComponent(DecompressButton))
                                .addGap(60, 60, 60)
                                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(28, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BrowseButtonActionPerformed
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setMultiSelectionEnabled(true); // Enable multiple file selection
        int result = fileChooser.showOpenDialog(this);

        if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
            selectedFiles = fileChooser.getSelectedFiles();

            // Prototype Pattern - update current selection
            currentSelection.setSelectedFiles(selectedFiles);
            currentSelection.setCompressionType((String) TypeComboBox.getSelectedItem());

            if (selectedFiles != null && selectedFiles.length > 0) {
                if (selectedFiles.length == 1) {
                    // Single file selected - show path
                    PathTextFiled.setText(selectedFiles[0].getAbsolutePath());
                    lblStatus.setText("File selected: " + selectedFiles[0].getName());
                } else {
                    // Multiple files selected - show count and names
                    StringBuilder fileNames = new StringBuilder();
                    for (int i = 0; i < Math.min(3, selectedFiles.length); i++) {
                        if (i > 0)
                            fileNames.append(", ");
                        fileNames.append(selectedFiles[i].getName());
                    }
                    if (selectedFiles.length > 3) {
                        fileNames.append(" ... and " + (selectedFiles.length - 3) + " more");
                    }

                    PathTextFiled.setText(selectedFiles.length + " files selected");
                    lblStatus.setText("Selected: " + fileNames.toString());
                }
            }
        }
    }// GEN-LAST:event_BrowseButtonActionPerformed

    private void CompressButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CompressButtonActionPerformed
        String compressionType = (String) TypeComboBox.getSelectedItem();

        // Check if files are selected
        if (selectedFiles == null || selectedFiles.length == 0) {
            lblStatus.setText("Please select file(s) first!");
            return;
        }

        try {
            lblStatus.setText("Compressing...");

            // Get compressor from CompressionFactory
            Compressor compressor = CompressionFactory.createCompressor(compressionType);
            boolean success;

            if (selectedFiles.length == 1) {
                // Single file compression - use existing logic
                String filePath = selectedFiles[0].getAbsolutePath();
                FileHandler fileHandler = FileHandler.getInstance();

                if (!fileHandler.fileExists(filePath)) {
                    lblStatus.setText("File does not exist!");
                    return;
                }

                // Factory Pattern: Detect file type and get appropriate processor
                String extension = FileTypeFactory.getFileExtension(filePath);
                FileTypeProcessor processor = FileTypeFactory.getProcessor(extension);

                // Show user which processor is being used
                System.out.println("\n=== FILE TYPE PROCESSING ===");
                System.out.println("File: " + selectedFiles[0].getName());
                System.out.println("Extension: " + extension);
                System.out.println("Processor Type: " + processor.getFileType());
                System.out.println("============================\n");

                lblStatus.setText("Processing as " + processor.getFileType() + " file...");

                // Read and process the file data
                byte[] rawData = fileHandler.readFile(filePath);
                if (rawData == null) {
                    lblStatus.setText("Failed to read file!");
                    return;
                }

                // Apply file type specific preprocessing
                byte[] processedData = processor.prepareForCompression(rawData);

                // Note: The processed data is used internally by the compression manager
                // We still pass the file path for the actual compression
                lblStatus.setText("Compressing " + processor.getFileType() + " file...");
                success = compressionManager.compressFile(filePath, compressor, ProgressBar);

            } else {
                // Multiple files compression - use new multi-file logic
                String[] filePaths = new String[selectedFiles.length];

                // Process each file according to its type
                System.out.println("\n=== PROCESSING MULTIPLE FILES ===");
                for (int i = 0; i < selectedFiles.length; i++) {
                    filePaths[i] = selectedFiles[i].getAbsolutePath();

                    // Get processor for each file
                    String ext = FileTypeFactory.getFileExtension(filePaths[i]);
                    FileTypeProcessor proc = FileTypeFactory.getProcessor(ext);
                    System.out.println((i + 1) + ". " + selectedFiles[i].getName()
                            + " - " + proc.getFileType() + " file");
                }
                System.out.println("=================================\n");

                // Builder Pattern - construct output archive name step by step
                String outputDir = selectedFiles[0].getParent();
                String outputArchivePath = new ArchiveNameBuilder()
                        .withPrefix("compressed_archive")
                        .withTimestamp()
                        .withExtension(compressor.getExtension())
                        .buildWithDirectory(outputDir);

                success = compressionManager.compressFiles(filePaths, outputArchivePath, compressor, ProgressBar);
            }

            if (success) {
                lblStatus.setText("Compression completed successfully!");
            } else {
                lblStatus.setText("Compression failed!");
            }

        } catch (Exception e) {
            lblStatus.setText("Error: " + e.getMessage());
            e.printStackTrace();
        }

    }// GEN-LAST:event_CompressButtonActionPerformed

    private void DecompressButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_DecompressButtonActionPerformed
        // TODO add your handling code here:
        String filePath = PathTextFiled.getText();
        String compressionType = (String) TypeComboBox.getSelectedItem();

        if (filePath.isEmpty()) {
            lblStatus.setText("Please select a file first!");
            return;
        }

        FileHandler fileHandler = FileHandler.getInstance();

        if (!fileHandler.fileExists(filePath)) {
            lblStatus.setText("File does not exist!");
            return;
        }

        try {
            lblStatus.setText("Decompressing...");

            // 1️⃣ Get compressor for algorithm
            Compressor compressor = CompressionFactory.createCompressor(compressionType);

            // 2️⃣ Call singleton manager
            boolean success = compressionManager.decompressFile(filePath, compressor, ProgressBar); // = false

            if (success) {
                lblStatus.setText("Decompression completed successfully!");
            } else {
                lblStatus.setText("Decompression failed!");
            }

        } catch (Exception e) {
            lblStatus.setText("Error: " + e.getMessage());
            e.printStackTrace();
        }

    }// GEN-LAST:event_DecompressButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileSelectionPanel.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileSelectionPanel.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileSelectionPanel.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileSelectionPanel.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileSelectionPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BrowseButton;
    private javax.swing.JButton CompressButton;
    private javax.swing.JButton DecompressButton;
    private javax.swing.JTextField PathTextFiled;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JComboBox<String> TypeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
}
